version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    restart: always
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config
